[package]
name = "rust-leetcode"
version = "0.1.0"
edition = "2021"
description = "pass leetcode using rust"
authors = ["xpecya<xpecya@gmail.com>"]
repository = "https://github.com/Xpecya/rust-leetcode.git"
license = "GNU GPLv2"
keywords = ["leetcode"]
